/**
 * S&P 500 ticker → company name mapping for search autocomplete.
 * This is a static list used only for the search UI — real data
 * is fetched from the backend for whatever tickers the user selects.
 */
export const SP500_TICKERS: Record<string, string> = {
  AAPL: "Apple Inc",
  ABBV: "AbbVie Inc",
  ABT: "Abbott Laboratories",
  ACN: "Accenture plc",
  ADBE: "Adobe Inc",
  ADI: "Analog Devices Inc",
  ADM: "Archer-Daniels-Midland Co",
  ADP: "Automatic Data Processing",
  ADSK: "Autodesk Inc",
  AEE: "Ameren Corp",
  AEP: "American Electric Power",
  AES: "AES Corp",
  AFL: "Aflac Inc",
  AIG: "American International Group",
  AIZ: "Assurant Inc",
  AJG: "Arthur J Gallagher & Co",
  AKAM: "Akamai Technologies",
  ALB: "Albemarle Corp",
  ALGN: "Align Technology Inc",
  ALK: "Alaska Air Group",
  ALL: "Allstate Corp",
  ALLE: "Allegion plc",
  AMAT: "Applied Materials Inc",
  AMCR: "Amcor plc",
  AMD: "Advanced Micro Devices",
  AME: "AMETEK Inc",
  AMGN: "Amgen Inc",
  AMP: "Ameriprise Financial",
  AMT: "American Tower Corp",
  AMZN: "Amazon.com Inc",
  ANET: "Arista Networks Inc",
  ANSS: "ANSYS Inc",
  AON: "Aon plc",
  AOS: "AO Smith Corp",
  APA: "APA Corp",
  APD: "Air Products & Chemicals",
  APH: "Amphenol Corp",
  APTV: "Aptiv plc",
  ARE: "Alexandria Real Estate",
  ATO: "Atmos Energy Corp",
  ATVI: "Activision Blizzard",
  AVB: "AvalonBay Communities",
  AVGO: "Broadcom Inc",
  AVY: "Avery Dennison Corp",
  AWK: "American Water Works",
  AXP: "American Express Co",
  AZO: "AutoZone Inc",
  BA: "Boeing Co",
  BAC: "Bank of America Corp",
  BAX: "Baxter International",
  BBWI: "Bath & Body Works Inc",
  BBY: "Best Buy Co Inc",
  BDX: "Becton Dickinson & Co",
  BEN: "Franklin Resources Inc",
  BF_B: "Brown-Forman Corp",
  BIIB: "Biogen Inc",
  BIO: "Bio-Rad Laboratories",
  BK: "Bank of New York Mellon",
  BKNG: "Booking Holdings Inc",
  BKR: "Baker Hughes Co",
  BLK: "BlackRock Inc",
  BMY: "Bristol-Myers Squibb",
  BR: "Broadridge Financial",
  BRK_B: "Berkshire Hathaway",
  BRO: "Brown & Brown Inc",
  BSX: "Boston Scientific Corp",
  BWA: "BorgWarner Inc",
  BXP: "BXP Inc",
  C: "Citigroup Inc",
  CAG: "Conagra Brands Inc",
  CAH: "Cardinal Health Inc",
  CARR: "Carrier Global Corp",
  CAT: "Caterpillar Inc",
  CB: "Chubb Ltd",
  CBOE: "Cboe Global Markets",
  CBRE: "CBRE Group Inc",
  CCI: "Crown Castle Inc",
  CCL: "Carnival Corp",
  CDAY: "Ceridian HCM Holding",
  CDNS: "Cadence Design Systems",
  CDW: "CDW Corp",
  CE: "Celanese Corp",
  CEG: "Constellation Energy",
  CF: "CF Industries Holdings",
  CFG: "Citizens Financial Group",
  CHD: "Church & Dwight Co",
  CHRW: "CH Robinson Worldwide",
  CHTR: "Charter Communications",
  CI: "Cigna Group",
  CINF: "Cincinnati Financial",
  CL: "Colgate-Palmolive Co",
  CLX: "Clorox Co",
  CMA: "Comerica Inc",
  CMCSA: "Comcast Corp",
  CME: "CME Group Inc",
  CMG: "Chipotle Mexican Grill",
  CMI: "Cummins Inc",
  CMS: "CMS Energy Corp",
  CNC: "Centene Corp",
  CNP: "CenterPoint Energy",
  COF: "Capital One Financial",
  COO: "Cooper Companies",
  COP: "ConocoPhillips",
  COST: "Costco Wholesale Corp",
  CPB: "Campbell Soup Co",
  CPRT: "Copart Inc",
  CPT: "Camden Property Trust",
  CRL: "Charles River Labs",
  CRM: "Salesforce Inc",
  CRWD: "CrowdStrike Holdings",
  CSCO: "Cisco Systems Inc",
  CSGP: "CoStar Group Inc",
  CSX: "CSX Corp",
  CTAS: "Cintas Corp",
  CTLT: "Catalent Inc",
  CTRA: "Coterra Energy Inc",
  CTSH: "Cognizant Technology",
  CTVA: "Corteva Inc",
  CVS: "CVS Health Corp",
  CVX: "Chevron Corp",
  CZR: "Caesars Entertainment",
  D: "Dominion Energy Inc",
  DAL: "Delta Air Lines Inc",
  DD: "DuPont de Nemours Inc",
  DE: "Deere & Co",
  DECK: "Deckers Outdoor Corp",
  DFS: "Discover Financial",
  DG: "Dollar General Corp",
  DGX: "Quest Diagnostics Inc",
  DHI: "DR Horton Inc",
  DHR: "Danaher Corp",
  DIS: "Walt Disney Co",
  DISH: "DISH Network Corp",
  DLTR: "Dollar Tree Inc",
  DOV: "Dover Corp",
  DOW: "Dow Inc",
  DPZ: "Domino's Pizza Inc",
  DRI: "Darden Restaurants",
  DTE: "DTE Energy Co",
  DUK: "Duke Energy Corp",
  DVA: "DaVita Inc",
  DVN: "Devon Energy Corp",
  DXCM: "DexCom Inc",
  EA: "Electronic Arts Inc",
  EBAY: "eBay Inc",
  ECL: "Ecolab Inc",
  ED: "Consolidated Edison",
  EFX: "Equifax Inc",
  EIX: "Edison International",
  EL: "Estee Lauder Companies",
  EMN: "Eastman Chemical Co",
  EMR: "Emerson Electric Co",
  ENPH: "Enphase Energy Inc",
  EOG: "EOG Resources Inc",
  EPAM: "EPAM Systems Inc",
  EQIX: "Equinix Inc",
  EQR: "Equity Residential",
  EQT: "EQT Corp",
  ES: "Eversource Energy",
  ESS: "Essex Property Trust",
  ETN: "Eaton Corp plc",
  ETR: "Entergy Corp",
  ETSY: "Etsy Inc",
  EVRG: "Evergy Inc",
  EW: "Edwards Lifesciences",
  EXC: "Exelon Corp",
  EXPD: "Expeditors International",
  EXPE: "Expedia Group Inc",
  EXR: "Extra Space Storage",
  F: "Ford Motor Co",
  FANG: "Diamondback Energy",
  FAST: "Fastenal Co",
  FBHS: "Fortune Brands Home",
  FCX: "Freeport-McMoRan Inc",
  FDS: "FactSet Research Systems",
  FDX: "FedEx Corp",
  FE: "FirstEnergy Corp",
  FFIV: "F5 Inc",
  FI: "Fiserv Inc",
  FICO: "Fair Isaac Corp",
  FIS: "Fidelity National Info",
  FISV: "Fiserv Inc",
  FITB: "Fifth Third Bancorp",
  FLT: "Fleetcor Technologies",
  FMC: "FMC Corp",
  FOX: "Fox Corp",
  FOXA: "Fox Corp Class A",
  FRC: "First Republic Bank",
  FRT: "Federal Realty Trust",
  FSLR: "First Solar Inc",
  FTNT: "Fortinet Inc",
  FTV: "Fortive Corp",
  GD: "General Dynamics Corp",
  GE: "General Electric Co",
  GEHC: "GE HealthCare Technologies",
  GILD: "Gilead Sciences Inc",
  GIS: "General Mills Inc",
  GL: "Globe Life Inc",
  GLW: "Corning Inc",
  GM: "General Motors Co",
  GNRC: "Generac Holdings Inc",
  GOOG: "Alphabet Inc Class C",
  GOOGL: "Alphabet Inc",
  GPC: "Genuine Parts Co",
  GPN: "Global Payments Inc",
  GRMN: "Garmin Ltd",
  GS: "Goldman Sachs Group",
  GWW: "WW Grainger Inc",
  HAL: "Halliburton Co",
  HAS: "Hasbro Inc",
  HBAN: "Huntington Bancshares",
  HCA: "HCA Healthcare Inc",
  HOLX: "Hologic Inc",
  HD: "Home Depot Inc",
  PEAK: "Healthpeak Properties",
  HES: "Hess Corp",
  HIG: "Hartford Financial",
  HII: "Huntington Ingalls",
  HLT: "Hilton Worldwide",
  HON: "Honeywell International",
  HPE: "Hewlett Packard Enterprise",
  HPQ: "HP Inc",
  HRL: "Hormel Foods Corp",
  HSIC: "Henry Schein Inc",
  HST: "Host Hotels & Resorts",
  HSY: "Hershey Co",
  HUBB: "Hubbell Inc",
  HUM: "Humana Inc",
  HWM: "Howmet Aerospace Inc",
  IBM: "International Business Machines",
  ICE: "Intercontinental Exchange",
  IDXX: "IDEXX Laboratories",
  IEX: "IDEX Corp",
  IFF: "International Flavors",
  ILMN: "Illumina Inc",
  INCY: "Incyte Corp",
  INTC: "Intel Corp",
  INTU: "Intuit Inc",
  INVH: "Invitation Homes Inc",
  IP: "International Paper Co",
  IPG: "Interpublic Group",
  IQV: "IQVIA Holdings Inc",
  IR: "Ingersoll Rand Inc",
  IRM: "Iron Mountain Inc",
  ISRG: "Intuitive Surgical Inc",
  IT: "Gartner Inc",
  ITW: "Illinois Tool Works",
  IVZ: "Invesco Ltd",
  J: "Jacobs Solutions Inc",
  JBHT: "JB Hunt Transport",
  JCI: "Johnson Controls",
  JKHY: "Jack Henry & Associates",
  JNJ: "Johnson & Johnson",
  JNPR: "Juniper Networks Inc",
  JPM: "JPMorgan Chase & Co",
  K: "Kellanova",
  KDP: "Keurig Dr Pepper Inc",
  KEY: "KeyCorp",
  KEYS: "Keysight Technologies",
  KHC: "Kraft Heinz Co",
  KIM: "Kimco Realty Corp",
  KLAC: "KLA Corp",
  KMB: "Kimberly-Clark Corp",
  KMI: "Kinder Morgan Inc",
  KMX: "CarMax Inc",
  KO: "Coca-Cola Co",
  KR: "Kroger Co",
  L: "Loews Corp",
  LDOS: "Leidos Holdings Inc",
  LEN: "Lennar Corp",
  LH: "Labcorp Holdings Inc",
  LHX: "L3Harris Technologies",
  LIN: "Linde plc",
  LKQ: "LKQ Corp",
  LLY: "Eli Lilly & Co",
  LMT: "Lockheed Martin Corp",
  LNC: "Lincoln National Corp",
  LNT: "Alliant Energy Corp",
  LOW: "Lowe's Companies Inc",
  LRCX: "Lam Research Corp",
  LULU: "Lululemon Athletica",
  LUV: "Southwest Airlines Co",
  LVS: "Las Vegas Sands Corp",
  LW: "Lamb Weston Holdings",
  LYB: "LyondellBasell Industries",
  LYV: "Live Nation Entertainment",
  MA: "Mastercard Inc",
  MAA: "Mid-America Apartment",
  MAR: "Marriott International",
  MAS: "Masco Corp",
  MCD: "McDonald's Corp",
  MCHP: "Microchip Technology",
  MCK: "McKesson Corp",
  MCO: "Moody's Corp",
  MDLZ: "Mondelez International",
  MDT: "Medtronic plc",
  MET: "MetLife Inc",
  META: "Meta Platforms Inc",
  MGM: "MGM Resorts International",
  MHK: "Mohawk Industries Inc",
  MKC: "McCormick & Co Inc",
  MKTX: "MarketAxess Holdings",
  MLM: "Martin Marietta Materials",
  MMC: "Marsh & McLennan",
  MMM: "3M Co",
  MNST: "Monster Beverage Corp",
  MO: "Altria Group Inc",
  MOH: "Molina Healthcare Inc",
  MOS: "Mosaic Co",
  MPC: "Marathon Petroleum Corp",
  MPWR: "Monolithic Power Systems",
  MRK: "Merck & Co Inc",
  MRNA: "Moderna Inc",
  MRO: "Marathon Oil Corp",
  MS: "Morgan Stanley",
  MSCI: "MSCI Inc",
  MSFT: "Microsoft Corp",
  MSI: "Motorola Solutions Inc",
  MTB: "M&T Bank Corp",
  MTCH: "Match Group Inc",
  MTD: "Mettler-Toledo International",
  MU: "Micron Technology Inc",
  NCLH: "Norwegian Cruise Line",
  NDAQ: "Nasdaq Inc",
  NDSN: "Nordson Corp",
  NEE: "NextEra Energy Inc",
  NEM: "Newmont Corp",
  NFLX: "Netflix Inc",
  NI: "NiSource Inc",
  NKE: "Nike Inc",
  NOC: "Northrop Grumman Corp",
  NOW: "ServiceNow Inc",
  NRG: "NRG Energy Inc",
  NSC: "Norfolk Southern Corp",
  NTAP: "NetApp Inc",
  NTRS: "Northern Trust Corp",
  NUE: "Nucor Corp",
  NVDA: "NVIDIA Corp",
  NVR: "NVR Inc",
  NWL: "Newell Brands Inc",
  NWS: "News Corp",
  NWSA: "News Corp Class A",
  NXPI: "NXP Semiconductors",
  O: "Realty Income Corp",
  ODFL: "Old Dominion Freight",
  OGN: "Organon & Co",
  OKE: "ONEOK Inc",
  OMC: "Omnicom Group Inc",
  ON: "ON Semiconductor Corp",
  ORCL: "Oracle Corp",
  ORLY: "O'Reilly Automotive",
  OTIS: "Otis Worldwide Corp",
  OXY: "Occidental Petroleum",
  PARA: "Paramount Global",
  PAYC: "Paycom Software Inc",
  PAYX: "Paychex Inc",
  PCAR: "PACCAR Inc",
  PCG: "PG&E Corp",
  PEG: "Public Service Enterprise",
  PEP: "PepsiCo Inc",
  PFE: "Pfizer Inc",
  PFG: "Principal Financial Group",
  PG: "Procter & Gamble Co",
  PGR: "Progressive Corp",
  PH: "Parker-Hannifin Corp",
  PHM: "PulteGroup Inc",
  PKG: "Packaging Corp of America",
  PKI: "PerkinElmer Inc",
  PLD: "Prologis Inc",
  PLTR: "Palantir Technologies",
  PM: "Philip Morris International",
  PNC: "PNC Financial Services",
  PNR: "Pentair plc",
  PNW: "Pinnacle West Capital",
  POOL: "Pool Corp",
  PPG: "PPG Industries Inc",
  PPL: "PPL Corp",
  PRU: "Prudential Financial",
  PSA: "Public Storage",
  PSX: "Phillips 66",
  PTC: "PTC Inc",
  PVH: "PVH Corp",
  PWR: "Quanta Services Inc",
  PXD: "Pioneer Natural Resources",
  PYPL: "PayPal Holdings Inc",
  QCOM: "Qualcomm Inc",
  QRVO: "Qorvo Inc",
  RCL: "Royal Caribbean Cruises",
  RE: "Everest Group Ltd",
  REG: "Regency Centers Corp",
  REGN: "Regeneron Pharmaceuticals",
  RF: "Regions Financial Corp",
  RHI: "Robert Half International",
  RJF: "Raymond James Financial",
  RL: "Ralph Lauren Corp",
  RMD: "ResMed Inc",
  ROK: "Rockwell Automation",
  ROL: "Rollins Inc",
  ROP: "Roper Technologies Inc",
  ROST: "Ross Stores Inc",
  RSG: "Republic Services Inc",
  RTX: "RTX Corp",
  RVTY: "Revvity Inc",
  SBAC: "SBA Communications",
  SBUX: "Starbucks Corp",
  SCHW: "Charles Schwab Corp",
  SEE: "Sealed Air Corp",
  SHW: "Sherwin-Williams Co",
  SIVB: "SVB Financial Group",
  SJM: "JM Smucker Co",
  SLB: "Schlumberger Ltd",
  SMCI: "Super Micro Computer",
  SNA: "Snap-on Inc",
  SNPS: "Synopsys Inc",
  SO: "Southern Co",
  SOFI: "SoFi Technologies",
  SPG: "Simon Property Group",
  SPGI: "S&P Global Inc",
  SRE: "Sempra",
  STE: "STERIS plc",
  STLD: "Steel Dynamics Inc",
  STT: "State Street Corp",
  STX: "Seagate Technology",
  STZ: "Constellation Brands",
  SWK: "Stanley Black & Decker",
  SWKS: "Skyworks Solutions",
  SYF: "Synchrony Financial",
  SYK: "Stryker Corp",
  SYY: "Sysco Corp",
  T: "AT&T Inc",
  TAP: "Molson Coors Beverage",
  TDG: "TransDigm Group Inc",
  TDY: "Teledyne Technologies",
  TECH: "Bio-Techne Corp",
  TEL: "TE Connectivity Ltd",
  TER: "Teradyne Inc",
  TFC: "Truist Financial Corp",
  TFX: "Teleflex Inc",
  TGT: "Target Corp",
  TJX: "TJX Companies Inc",
  TMO: "Thermo Fisher Scientific",
  TMUS: "T-Mobile US Inc",
  TPR: "Tapestry Inc",
  TRGP: "Targa Resources Corp",
  TRMB: "Trimble Inc",
  TROW: "T Rowe Price Group",
  TRV: "Travelers Companies",
  TSCO: "Tractor Supply Co",
  TSLA: "Tesla Inc",
  TSN: "Tyson Foods Inc",
  TT: "Trane Technologies plc",
  TTWO: "Take-Two Interactive",
  TXN: "Texas Instruments Inc",
  TXT: "Textron Inc",
  TYL: "Tyler Technologies Inc",
  UAL: "United Airlines Holdings",
  UDR: "UDR Inc",
  UHS: "Universal Health Services",
  ULTA: "Ulta Beauty Inc",
  UNH: "UnitedHealth Group Inc",
  UNP: "Union Pacific Corp",
  UPS: "United Parcel Service",
  URI: "United Rentals Inc",
  USB: "US Bancorp",
  V: "Visa Inc",
  VFC: "VF Corp",
  VICI: "VICI Properties Inc",
  VLO: "Valero Energy Corp",
  VMC: "Vulcan Materials Co",
  VRSK: "Verisk Analytics Inc",
  VRSN: "VeriSign Inc",
  VRTX: "Vertex Pharmaceuticals",
  VTR: "Ventas Inc",
  VTRS: "Viatris Inc",
  VZ: "Verizon Communications",
  WAB: "Westinghouse Air Brake",
  WAT: "Waters Corp",
  WBA: "Walgreens Boots Alliance",
  WBD: "Warner Bros Discovery",
  WDC: "Western Digital Corp",
  WEC: "WEC Energy Group",
  WELL: "Welltower Inc",
  WFC: "Wells Fargo & Co",
  WHR: "Whirlpool Corp",
  WM: "Waste Management Inc",
  WMB: "Williams Companies Inc",
  WMT: "Walmart Inc",
  WRB: "WR Berkley Corp",
  WRK: "WestRock Co",
  WST: "West Pharmaceutical",
  WTW: "Willis Towers Watson",
  WY: "Weyerhaeuser Co",
  WYNN: "Wynn Resorts Ltd",
  XEL: "Xcel Energy Inc",
  XOM: "Exxon Mobil Corp",
  XRAY: "Dentsply Sirona Inc",
  XYL: "Xylem Inc",
  YUM: "Yum! Brands Inc",
  ZBH: "Zimmer Biomet Holdings",
  ZBRA: "Zebra Technologies",
  ZION: "Zions Bancorporation",
  ZTS: "Zoetis Inc",
};

/** All searchable tickers, sorted alphabetically */
export const TICKER_LIST = Object.keys(SP500_TICKERS).sort();
